<a href="https://colab.research.google.com/github/Nafiz-kodar/Machine_learning_project/blob/main/422_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Features Description

Age → Age of the individual (years)

Gender → Gender of the individual

Height → Height of the individual (in meters)

Weight → Weight of the individual (in kilograms)

CALC → Consumption of Alcohol

FAVC → Frequent consumption of High Caloric food

FCVC → Frequency of Consumption of Vegetables

NCP → Number of main meals (per day)

SCC → Calories Consumption Monitoring

SMOKE → Smoking habit

CH2O → Consumption of Water (daily water intake)

family_history_with_overweight → Family history with overweight/obesity

FAF → Frequency of Physical Activity

TUE → Time Using Technology devices

CAEC → Consumption of food Between meals

MTRANS → Mode of Transportation

NObeyesdad → Nutritional Obesity Level (Obesity diagnosis)

## **Data Cleaning**

**Libraries**

In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('/content/Updated_Obesity_Dataset.csv')

In [3]:
df.shape
df.columns

Index(['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP',
       'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE',
       'CAEC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [4]:
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   float64
 1   Gender                          2100 non-null   object
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2090 non-null   float64
 11  family_history_with_overweight  2090 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [6]:
df['NObeyesdad'].value_counts()

NObeyesdad
Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: count, dtype: int64

Null Vals

In [7]:
df.isnull().sum()

Age                                0
Gender                            11
Height                             0
Weight                             0
CALC                               0
FAVC                               0
FCVC                               0
NCP                                0
SCC                                0
SMOKE                              0
CH2O                              21
family_history_with_overweight    21
FAF                                0
TUE                                0
CAEC                               0
MTRANS                             0
NObeyesdad                         0
dtype: int64

In [8]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

/tmp/ipython-input-700870124.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

In [9]:
df['CH2O'].fillna(df['CH2O'].median(), inplace=True)

/tmp/ipython-input-2400786316.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CH2O'].fillna(df['CH2O'].median(), inplace=True)

In [10]:
df['family_history_with_overweight'].fillna(df['family_history_with_overweight'].mode()[0],inplace=True)

/tmp/ipython-input-2629551306.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['family_history_with_overweight'].fillna(df['family_history_with_overweight'].mode()[0],inplace=True)

In [11]:
df.isnull().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

Duplicates

In [12]:
df.duplicated().sum()

np.int64(23)

In [13]:
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
97,21.0,Female,1.52,42.0,Sometimes,no,3.0,1.0,no,no,1.0,no,0.0,0.0,Frequently,Public_Transportation,Insufficient_Weight
98,21.0,Female,1.52,42.0,Sometimes,no,3.0,1.0,no,no,1.0,no,0.0,0.0,Frequently,Public_Transportation,Insufficient_Weight
105,25.0,Female,1.57,55.0,Sometimes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
106,25.0,Female,1.57,55.0,Sometimes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
145,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
174,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
179,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
184,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
208,22.0,Female,1.69,65.0,Sometimes,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
209,22.0,Female,1.69,65.0,Sometimes,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
282,18.0,Female,1.62,55.0,no,yes,2.0,3.0,no,no,1.0,yes,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
295,16.0,Female,1.66,58.0,no,no,2.0,1.0,no,no,1.0,no,0.0,1.0,Sometimes,Walking,Normal_Weight
309,16.0,Female,1.66,58.0,no,no,2.0,1.0,no,no,1.0,no,0.0,1.0,Sometimes,Walking,Normal_Weight
443,18.0,Male,1.72,53.0,Sometimes,yes,2.0,3.0,no,no,2.0,yes,0.0,2.0,Sometimes,Public_Transportation,Insufficient_Weight
460,18.0,Female,1.62,55.0,no,yes,2.0,3.0,no,no,1.0,yes,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
466,22.0,Male,1.74,75.0,no,yes,3.0,3.0,no,no,1.0,yes,1.0,0.0,Frequently,Automobile,Normal_Weight
467,22.0,Male,1.74,75.0,no,yes,3.0,3.0,no,no,1.0,yes,1.0,0.0,Frequently,Automobile,Normal_Weight
496,18.0,Male,1.72,53.0,Sometimes,yes,2.0,3.0,no,no,2.0,yes,0.0,2.0,Sometimes,Public_Transportation,Insufficient_Weight
523,21.0,Female,1.52,42.0,Sometimes,yes,3.0,1.0,no,no,1.0,no,0.0,0.0,Frequently,Public_Transportation,Insufficient_Weight
659,21.0,Female,1.52,42.0,Sometimes,yes,3.0,1.0,no,no,1.0,no,0.0,0.0,Frequently,Public_Transportation,Insufficient_Weight
663,21.0,Female,1.52,42.0,Sometimes,yes,3.0,1.0,no,no,1.0,no,0.0,0.0,Frequently,Public_Transportation,Insufficient_Weight
763,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
764,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
824,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
830,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
831,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
832,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
833,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
834,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
921,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
922,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I
923,21.0,Male,1.62,70.0,Sometimes,yes,2.0,1.0,no,no,3.0,no,1.0,0.0,no,Public_Transportation,Overweight_Level_I

In [14]:
df.drop_duplicates(inplace=True)

Scaling & Encoding

In [15]:
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns
print(numerical_features)

Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE'], dtype='object')

In [16]:
categorical_features = df.select_dtypes(include=['object']).columns
categorical_features

Index(['Gender', 'CALC', 'FAVC', 'SCC', 'SMOKE',
       'family_history_with_overweight', 'CAEC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

Train-test splitting

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [18]:
x=df.drop('NObeyesdad',axis=1)
y=df['NObeyesdad']

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=123)

In [20]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1670, 16)
(418, 16)
(1670,)
(418,)

In [21]:
categorical_features=x.select_dtypes(include=['object']).columns
numerical_features=x.select_dtypes(include=['int64', 'float64']).columns

In [22]:
scaler=StandardScaler()

x_train[numerical_features] = scaler.fit_transform(x_train[numerical_features])
x_test[numerical_features]= scaler.transform(x_test[numerical_features])

In [23]:
print('Head of x_train after scaling:')
display(x_train[numerical_features].head())

Head of x_train after scaling:

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
322,-0.209108,0.513896,-1.166528,1.073010,0.389266,-0.010500,1.175146,-1.084398
1167,-0.584893,-2.041286,-0.832202,-0.263396,0.667028,-0.010500,0.118220,0.985791
1733,1.013584,0.874490,1.273563,-0.172655,0.389266,0.482033,-0.515581,0.429187
457,-0.854503,-2.141203,-1.581936,-0.820096,0.389266,-1.652944,-1.181665,-1.084398
2083,0.028035,-0.406457,0.988957,1.073010,0.389266,1.027893,-0.827007,-0.641875

In [24]:
print('\nMean of numerical features in x_train after scaling:')
display(x_train[numerical_features].mean())
print('\nStandard deviation of numerical features in x_train after scaling:')
display(x_train[numerical_features].std())

Mean of numerical features in x_train after scaling:

Age      -1.957184e-16
Height    1.378538e-15
Weight    3.637809e-16
FCVC      1.840178e-16
NCP      -4.595127e-16
CH2O     -3.403798e-17
FAF       4.254747e-18
TUE       8.509494e-18
dtype: float64

Standard deviation of numerical features in x_train after scaling:

Age       1.0003
Height    1.0003
Weight    1.0003
FCVC      1.0003
NCP       1.0003
CH2O      1.0003
FAF       1.0003
TUE       1.0003
dtype: float64

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in categorical_features:
    x_train[col] = le.fit_transform(x_train[col])
    x_test[col] = le.transform(x_test[col])

In [26]:
print('x_train after all transformations:')
display(x_train.head())
print('\nx_test after all transformations:')
display(x_test.head())

x_train after all transformations:

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS
322,-0.209108,0,0.513896,-1.166528,2,0,1.073010,0.389266,0,0,-0.010500,0,1.175146,-1.084398,1,3
1167,-0.584893,0,-2.041286,-0.832202,3,0,-0.263396,0.667028,0,0,-0.010500,1,0.118220,0.985791,2,3
1733,1.013584,1,0.874490,1.273563,2,1,-0.172655,0.389266,0,0,0.482033,1,-0.515581,0.429187,2,0
457,-0.854503,0,-2.141203,-1.581936,2,1,-0.820096,0.389266,0,0,-1.652944,0,-1.181665,-1.084398,2,3
2083,0.028035,0,-0.406457,0.988957,2,1,1.073010,0.389266,0,0,1.027893,1,-0.827007,-0.641875,2,3

x_test after all transformations:

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS
1423,2.464280,1,0.888647,0.511405,1,1,0.830253,-1.211359,0,0,1.124958,1,1.818210,0.399493,2,0
144,-0.370457,1,-0.972960,-0.751120,2,0,-0.820096,1.715050,1,0,1.631944,1,1.175146,2.198899,2,3
1633,0.997014,1,1.059444,1.291717,2,1,-0.198269,0.389266,0,0,-0.008516,1,-0.238367,-0.794355,2,0
690,-1.093016,1,0.598413,-1.314024,2,1,-0.413116,-0.085961,0,0,0.188648,0,-0.005156,0.325482,2,3
1805,0.259172,0,-0.243785,0.682221,2,1,1.073010,0.389266,0,0,-0.558814,1,-0.933786,0.120917,2,3

# **NAIVE BAYES**

In [27]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [28]:
nb_y_pred = model.predict(x_test)
#print(y_pred)

In [29]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, nb_y_pred))
print(classification_report(y_test, nb_y_pred))
print(confusion_matrix(y_test, nb_y_pred))

Accuracy: 0.5598086124401914
                     precision    recall  f1-score   support

Insufficient_Weight       0.46      0.95      0.62        55
      Normal_Weight       0.50      0.09      0.16        53
     Obesity_Type_I       0.43      0.74      0.55        81
    Obesity_Type_II       0.68      0.84      0.75        58
   Obesity_Type_III       0.98      0.98      0.98        58
 Overweight_Level_I       0.36      0.07      0.11        60
Overweight_Level_II       0.47      0.13      0.21        53

           accuracy                           0.56       418
          macro avg       0.56      0.54      0.48       418
       weighted avg       0.55      0.56      0.49       418

[[52  2  0  0  0  1  0]
 [37  5  4  0  1  4  2]
 [ 0  1 60 15  0  0  5]
 [ 0  0  8 49  0  0  1]
 [ 0  0  0  1 57  0  0]
 [21  1 34  0  0  4  0]
 [ 3  1 33  7  0  2  7]]

# **KNN**

In [30]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
knn_y_pred = model.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))
print(confusion_matrix(y_test, knn_y_pred))

Accuracy: 0.8301435406698564
                     precision    recall  f1-score   support

Insufficient_Weight       0.79      0.98      0.88        55
      Normal_Weight       0.79      0.36      0.49        53
     Obesity_Type_I       0.83      0.90      0.86        81
    Obesity_Type_II       0.87      0.93      0.90        58
   Obesity_Type_III       1.00      1.00      1.00        58
 Overweight_Level_I       0.75      0.80      0.77        60
Overweight_Level_II       0.76      0.77      0.77        53

           accuracy                           0.83       418
          macro avg       0.83      0.82      0.81       418
       weighted avg       0.83      0.83      0.82       418

[[54  1  0  0  0  0  0]
 [11 19  2  2  0 12  7]
 [ 1  0 73  1  0  1  5]
 [ 0  0  3 54  0  1  0]
 [ 0  0  0  0 58  0  0]
 [ 2  2  5  2  0 48  1]
 [ 0  2  5  3  0  2 41]]